/*
 * AUTOGENERATED FILE
 * from genInterpreter.js
 * DO NOT EDIT 
 */
#include "vm.h"

#ifndef __INTERPRETER_H__
#define __INTERPRETER_H__
word_t u_run(uint8_t *ip);

#define QUIT 0
#define HELLO 1
#define PUSH_INT 2
#define LOG_INT 3
#define POP 4
#define ADD 5

#endif /* __INTERPRETER_H__ */
