/*
 * AUTOGENERATED FILE
 * from genInterpreter.js
 * DO NOT EDIT
 */
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include "interpreter.h"
#define sp u_stack

word_t u_run(uint8_t *ip) {
  word_t *h = u_heap;
  for(;;) {
    if(u_heap + heap_top >= sp) {
      printf("Error, stack limit reached\n");
      exit(-1);
    }
    switch(*ip++) {
      case QUIT:
        return 0;
      break;
      case HELLO:
        printf("Hello\n");
      break;
      case PUSH_INT:
        *--sp = *ip++;
      break;
      case LOG_INT:
        printf("LOG_INT %d\n", *sp);
      break;
      case POP:
        sp++;
      break;
      case ADD:
        ++sp;
        *sp = sp[-1] + sp[0];
      break;
    }
  }
}