/*
 * AUTOGENERATED FILE
 * from genInterpreter.js
 * DO NOT EDIT 
 */
#ifndef __OPS_H__
#define __OPS_H__

#define u_QUIT 0
#define u_HELLO 1
#define u_PUSH_INT 2
#define u_LOG_INT 3
#define u_POP 4
#define u_DUP 5
#define u_ADD 6
#define u_PUSH_N 7
#define u_TUPLE 8

#endif /* __OPS_H__ */
